package com.llsfw.core.model.standard;

import java.io.Serializable;
import java.util.Date;

public class TtOnlineUser implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_ONLINE_USER.ID
     *
     * @mbggenerated Sat Apr 19 13:01:25 CST 2014
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_ONLINE_USER.LOGIN_NAME
     *
     * @mbggenerated Sat Apr 19 13:01:25 CST 2014
     */
    private String loginName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_ONLINE_USER.LOGIN_HOST
     *
     * @mbggenerated Sat Apr 19 13:01:25 CST 2014
     */
    private String loginHost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_ONLINE_USER.LOGIN_SYSTEM_HOST
     *
     * @mbggenerated Sat Apr 19 13:01:25 CST 2014
     */
    private String loginSystemHost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_ONLINE_USER.LOGIN_USER_AGENT
     *
     * @mbggenerated Sat Apr 19 13:01:25 CST 2014
     */
    private String loginUserAgent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_ONLINE_USER.LOGIN_DATE
     *
     * @mbggenerated Sat Apr 19 13:01:25 CST 2014
     */
    private Date loginDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_ONLINE_USER.LOGIN_LAST_ACCESS_TIME
     *
     * @mbggenerated Sat Apr 19 13:01:25 CST 2014
     */
    private Date loginLastAccessTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_ONLINE_USER.LOGIN_TIME_OUT
     *
     * @mbggenerated Sat Apr 19 13:01:25 CST 2014
     */
    private Long loginTimeOut;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TT_ONLINE_USER
     *
     * @mbggenerated Sat Apr 19 13:01:25 CST 2014
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_ONLINE_USER.ID
     *
     * @return the value of TT_ONLINE_USER.ID
     *
     * @mbggenerated Sat Apr 19 13:01:25 CST 2014
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_ONLINE_USER.ID
     *
     * @param id the value for TT_ONLINE_USER.ID
     *
     * @mbggenerated Sat Apr 19 13:01:25 CST 2014
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_ONLINE_USER.LOGIN_NAME
     *
     * @return the value of TT_ONLINE_USER.LOGIN_NAME
     *
     * @mbggenerated Sat Apr 19 13:01:25 CST 2014
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_ONLINE_USER.LOGIN_NAME
     *
     * @param loginName the value for TT_ONLINE_USER.LOGIN_NAME
     *
     * @mbggenerated Sat Apr 19 13:01:25 CST 2014
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_ONLINE_USER.LOGIN_HOST
     *
     * @return the value of TT_ONLINE_USER.LOGIN_HOST
     *
     * @mbggenerated Sat Apr 19 13:01:25 CST 2014
     */
    public String getLoginHost() {
        return loginHost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_ONLINE_USER.LOGIN_HOST
     *
     * @param loginHost the value for TT_ONLINE_USER.LOGIN_HOST
     *
     * @mbggenerated Sat Apr 19 13:01:25 CST 2014
     */
    public void setLoginHost(String loginHost) {
        this.loginHost = loginHost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_ONLINE_USER.LOGIN_SYSTEM_HOST
     *
     * @return the value of TT_ONLINE_USER.LOGIN_SYSTEM_HOST
     *
     * @mbggenerated Sat Apr 19 13:01:25 CST 2014
     */
    public String getLoginSystemHost() {
        return loginSystemHost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_ONLINE_USER.LOGIN_SYSTEM_HOST
     *
     * @param loginSystemHost the value for TT_ONLINE_USER.LOGIN_SYSTEM_HOST
     *
     * @mbggenerated Sat Apr 19 13:01:25 CST 2014
     */
    public void setLoginSystemHost(String loginSystemHost) {
        this.loginSystemHost = loginSystemHost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_ONLINE_USER.LOGIN_USER_AGENT
     *
     * @return the value of TT_ONLINE_USER.LOGIN_USER_AGENT
     *
     * @mbggenerated Sat Apr 19 13:01:25 CST 2014
     */
    public String getLoginUserAgent() {
        return loginUserAgent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_ONLINE_USER.LOGIN_USER_AGENT
     *
     * @param loginUserAgent the value for TT_ONLINE_USER.LOGIN_USER_AGENT
     *
     * @mbggenerated Sat Apr 19 13:01:25 CST 2014
     */
    public void setLoginUserAgent(String loginUserAgent) {
        this.loginUserAgent = loginUserAgent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_ONLINE_USER.LOGIN_DATE
     *
     * @return the value of TT_ONLINE_USER.LOGIN_DATE
     *
     * @mbggenerated Sat Apr 19 13:01:25 CST 2014
     */
    public Date getLoginDate() {
        return loginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_ONLINE_USER.LOGIN_DATE
     *
     * @param loginDate the value for TT_ONLINE_USER.LOGIN_DATE
     *
     * @mbggenerated Sat Apr 19 13:01:25 CST 2014
     */
    public void setLoginDate(Date loginDate) {
        this.loginDate = loginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_ONLINE_USER.LOGIN_LAST_ACCESS_TIME
     *
     * @return the value of TT_ONLINE_USER.LOGIN_LAST_ACCESS_TIME
     *
     * @mbggenerated Sat Apr 19 13:01:25 CST 2014
     */
    public Date getLoginLastAccessTime() {
        return loginLastAccessTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_ONLINE_USER.LOGIN_LAST_ACCESS_TIME
     *
     * @param loginLastAccessTime the value for TT_ONLINE_USER.LOGIN_LAST_ACCESS_TIME
     *
     * @mbggenerated Sat Apr 19 13:01:25 CST 2014
     */
    public void setLoginLastAccessTime(Date loginLastAccessTime) {
        this.loginLastAccessTime = loginLastAccessTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_ONLINE_USER.LOGIN_TIME_OUT
     *
     * @return the value of TT_ONLINE_USER.LOGIN_TIME_OUT
     *
     * @mbggenerated Sat Apr 19 13:01:25 CST 2014
     */
    public Long getLoginTimeOut() {
        return loginTimeOut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_ONLINE_USER.LOGIN_TIME_OUT
     *
     * @param loginTimeOut the value for TT_ONLINE_USER.LOGIN_TIME_OUT
     *
     * @mbggenerated Sat Apr 19 13:01:25 CST 2014
     */
    public void setLoginTimeOut(Long loginTimeOut) {
        this.loginTimeOut = loginTimeOut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_ONLINE_USER
     *
     * @mbggenerated Sat Apr 19 13:01:25 CST 2014
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TtOnlineUser other = (TtOnlineUser) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getLoginName() == null ? other.getLoginName() == null : this.getLoginName().equals(other.getLoginName()))
            && (this.getLoginHost() == null ? other.getLoginHost() == null : this.getLoginHost().equals(other.getLoginHost()))
            && (this.getLoginSystemHost() == null ? other.getLoginSystemHost() == null : this.getLoginSystemHost().equals(other.getLoginSystemHost()))
            && (this.getLoginUserAgent() == null ? other.getLoginUserAgent() == null : this.getLoginUserAgent().equals(other.getLoginUserAgent()))
            && (this.getLoginDate() == null ? other.getLoginDate() == null : this.getLoginDate().equals(other.getLoginDate()))
            && (this.getLoginLastAccessTime() == null ? other.getLoginLastAccessTime() == null : this.getLoginLastAccessTime().equals(other.getLoginLastAccessTime()))
            && (this.getLoginTimeOut() == null ? other.getLoginTimeOut() == null : this.getLoginTimeOut().equals(other.getLoginTimeOut()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_ONLINE_USER
     *
     * @mbggenerated Sat Apr 19 13:01:25 CST 2014
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getLoginName() == null) ? 0 : getLoginName().hashCode());
        result = prime * result + ((getLoginHost() == null) ? 0 : getLoginHost().hashCode());
        result = prime * result + ((getLoginSystemHost() == null) ? 0 : getLoginSystemHost().hashCode());
        result = prime * result + ((getLoginUserAgent() == null) ? 0 : getLoginUserAgent().hashCode());
        result = prime * result + ((getLoginDate() == null) ? 0 : getLoginDate().hashCode());
        result = prime * result + ((getLoginLastAccessTime() == null) ? 0 : getLoginLastAccessTime().hashCode());
        result = prime * result + ((getLoginTimeOut() == null) ? 0 : getLoginTimeOut().hashCode());
        return result;
    }
}