package com.llsfw.core.model.standard;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TtScheduledTriggerLogCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TT_SCHEDULED_TRIGGER_LOG
     *
     * @mbggenerated Mon May 05 11:25:40 CST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TT_SCHEDULED_TRIGGER_LOG
     *
     * @mbggenerated Mon May 05 11:25:40 CST 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TT_SCHEDULED_TRIGGER_LOG
     *
     * @mbggenerated Mon May 05 11:25:40 CST 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_SCHEDULED_TRIGGER_LOG
     *
     * @mbggenerated Mon May 05 11:25:40 CST 2014
     */
    public TtScheduledTriggerLogCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_SCHEDULED_TRIGGER_LOG
     *
     * @mbggenerated Mon May 05 11:25:40 CST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_SCHEDULED_TRIGGER_LOG
     *
     * @mbggenerated Mon May 05 11:25:40 CST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_SCHEDULED_TRIGGER_LOG
     *
     * @mbggenerated Mon May 05 11:25:40 CST 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_SCHEDULED_TRIGGER_LOG
     *
     * @mbggenerated Mon May 05 11:25:40 CST 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_SCHEDULED_TRIGGER_LOG
     *
     * @mbggenerated Mon May 05 11:25:40 CST 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_SCHEDULED_TRIGGER_LOG
     *
     * @mbggenerated Mon May 05 11:25:40 CST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_SCHEDULED_TRIGGER_LOG
     *
     * @mbggenerated Mon May 05 11:25:40 CST 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_SCHEDULED_TRIGGER_LOG
     *
     * @mbggenerated Mon May 05 11:25:40 CST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_SCHEDULED_TRIGGER_LOG
     *
     * @mbggenerated Mon May 05 11:25:40 CST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_SCHEDULED_TRIGGER_LOG
     *
     * @mbggenerated Mon May 05 11:25:40 CST 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TT_SCHEDULED_TRIGGER_LOG
     *
     * @mbggenerated Mon May 05 11:25:40 CST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andLogidIsNull() {
            addCriterion("LOGID is null");
            return (Criteria) this;
        }

        public Criteria andLogidIsNotNull() {
            addCriterion("LOGID is not null");
            return (Criteria) this;
        }

        public Criteria andLogidEqualTo(String value) {
            addCriterion("LOGID =", value, "logid");
            return (Criteria) this;
        }

        public Criteria andLogidNotEqualTo(String value) {
            addCriterion("LOGID <>", value, "logid");
            return (Criteria) this;
        }

        public Criteria andLogidGreaterThan(String value) {
            addCriterion("LOGID >", value, "logid");
            return (Criteria) this;
        }

        public Criteria andLogidGreaterThanOrEqualTo(String value) {
            addCriterion("LOGID >=", value, "logid");
            return (Criteria) this;
        }

        public Criteria andLogidLessThan(String value) {
            addCriterion("LOGID <", value, "logid");
            return (Criteria) this;
        }

        public Criteria andLogidLessThanOrEqualTo(String value) {
            addCriterion("LOGID <=", value, "logid");
            return (Criteria) this;
        }

        public Criteria andLogidLike(String value) {
            addCriterion("LOGID like", value, "logid");
            return (Criteria) this;
        }

        public Criteria andLogidNotLike(String value) {
            addCriterion("LOGID not like", value, "logid");
            return (Criteria) this;
        }

        public Criteria andLogidIn(List<String> values) {
            addCriterion("LOGID in", values, "logid");
            return (Criteria) this;
        }

        public Criteria andLogidNotIn(List<String> values) {
            addCriterion("LOGID not in", values, "logid");
            return (Criteria) this;
        }

        public Criteria andLogidBetween(String value1, String value2) {
            addCriterion("LOGID between", value1, value2, "logid");
            return (Criteria) this;
        }

        public Criteria andLogidNotBetween(String value1, String value2) {
            addCriterion("LOGID not between", value1, value2, "logid");
            return (Criteria) this;
        }

        public Criteria andScheduledFireTimeIsNull() {
            addCriterion("SCHEDULED_FIRE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andScheduledFireTimeIsNotNull() {
            addCriterion("SCHEDULED_FIRE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andScheduledFireTimeEqualTo(Date value) {
            addCriterion("SCHEDULED_FIRE_TIME =", value, "scheduledFireTime");
            return (Criteria) this;
        }

        public Criteria andScheduledFireTimeNotEqualTo(Date value) {
            addCriterion("SCHEDULED_FIRE_TIME <>", value, "scheduledFireTime");
            return (Criteria) this;
        }

        public Criteria andScheduledFireTimeGreaterThan(Date value) {
            addCriterion("SCHEDULED_FIRE_TIME >", value, "scheduledFireTime");
            return (Criteria) this;
        }

        public Criteria andScheduledFireTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("SCHEDULED_FIRE_TIME >=", value, "scheduledFireTime");
            return (Criteria) this;
        }

        public Criteria andScheduledFireTimeLessThan(Date value) {
            addCriterion("SCHEDULED_FIRE_TIME <", value, "scheduledFireTime");
            return (Criteria) this;
        }

        public Criteria andScheduledFireTimeLessThanOrEqualTo(Date value) {
            addCriterion("SCHEDULED_FIRE_TIME <=", value, "scheduledFireTime");
            return (Criteria) this;
        }

        public Criteria andScheduledFireTimeIn(List<Date> values) {
            addCriterion("SCHEDULED_FIRE_TIME in", values, "scheduledFireTime");
            return (Criteria) this;
        }

        public Criteria andScheduledFireTimeNotIn(List<Date> values) {
            addCriterion("SCHEDULED_FIRE_TIME not in", values, "scheduledFireTime");
            return (Criteria) this;
        }

        public Criteria andScheduledFireTimeBetween(Date value1, Date value2) {
            addCriterion("SCHEDULED_FIRE_TIME between", value1, value2, "scheduledFireTime");
            return (Criteria) this;
        }

        public Criteria andScheduledFireTimeNotBetween(Date value1, Date value2) {
            addCriterion("SCHEDULED_FIRE_TIME not between", value1, value2, "scheduledFireTime");
            return (Criteria) this;
        }

        public Criteria andFireTimeIsNull() {
            addCriterion("FIRE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andFireTimeIsNotNull() {
            addCriterion("FIRE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andFireTimeEqualTo(Date value) {
            addCriterion("FIRE_TIME =", value, "fireTime");
            return (Criteria) this;
        }

        public Criteria andFireTimeNotEqualTo(Date value) {
            addCriterion("FIRE_TIME <>", value, "fireTime");
            return (Criteria) this;
        }

        public Criteria andFireTimeGreaterThan(Date value) {
            addCriterion("FIRE_TIME >", value, "fireTime");
            return (Criteria) this;
        }

        public Criteria andFireTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("FIRE_TIME >=", value, "fireTime");
            return (Criteria) this;
        }

        public Criteria andFireTimeLessThan(Date value) {
            addCriterion("FIRE_TIME <", value, "fireTime");
            return (Criteria) this;
        }

        public Criteria andFireTimeLessThanOrEqualTo(Date value) {
            addCriterion("FIRE_TIME <=", value, "fireTime");
            return (Criteria) this;
        }

        public Criteria andFireTimeIn(List<Date> values) {
            addCriterion("FIRE_TIME in", values, "fireTime");
            return (Criteria) this;
        }

        public Criteria andFireTimeNotIn(List<Date> values) {
            addCriterion("FIRE_TIME not in", values, "fireTime");
            return (Criteria) this;
        }

        public Criteria andFireTimeBetween(Date value1, Date value2) {
            addCriterion("FIRE_TIME between", value1, value2, "fireTime");
            return (Criteria) this;
        }

        public Criteria andFireTimeNotBetween(Date value1, Date value2) {
            addCriterion("FIRE_TIME not between", value1, value2, "fireTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNull() {
            addCriterion("END_TIME is null");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNotNull() {
            addCriterion("END_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andEndTimeEqualTo(Date value) {
            addCriterion("END_TIME =", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotEqualTo(Date value) {
            addCriterion("END_TIME <>", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThan(Date value) {
            addCriterion("END_TIME >", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("END_TIME >=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThan(Date value) {
            addCriterion("END_TIME <", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThanOrEqualTo(Date value) {
            addCriterion("END_TIME <=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIn(List<Date> values) {
            addCriterion("END_TIME in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotIn(List<Date> values) {
            addCriterion("END_TIME not in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeBetween(Date value1, Date value2) {
            addCriterion("END_TIME between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotBetween(Date value1, Date value2) {
            addCriterion("END_TIME not between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andJobRunTimeIsNull() {
            addCriterion("JOB_RUN_TIME is null");
            return (Criteria) this;
        }

        public Criteria andJobRunTimeIsNotNull() {
            addCriterion("JOB_RUN_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andJobRunTimeEqualTo(Long value) {
            addCriterion("JOB_RUN_TIME =", value, "jobRunTime");
            return (Criteria) this;
        }

        public Criteria andJobRunTimeNotEqualTo(Long value) {
            addCriterion("JOB_RUN_TIME <>", value, "jobRunTime");
            return (Criteria) this;
        }

        public Criteria andJobRunTimeGreaterThan(Long value) {
            addCriterion("JOB_RUN_TIME >", value, "jobRunTime");
            return (Criteria) this;
        }

        public Criteria andJobRunTimeGreaterThanOrEqualTo(Long value) {
            addCriterion("JOB_RUN_TIME >=", value, "jobRunTime");
            return (Criteria) this;
        }

        public Criteria andJobRunTimeLessThan(Long value) {
            addCriterion("JOB_RUN_TIME <", value, "jobRunTime");
            return (Criteria) this;
        }

        public Criteria andJobRunTimeLessThanOrEqualTo(Long value) {
            addCriterion("JOB_RUN_TIME <=", value, "jobRunTime");
            return (Criteria) this;
        }

        public Criteria andJobRunTimeIn(List<Long> values) {
            addCriterion("JOB_RUN_TIME in", values, "jobRunTime");
            return (Criteria) this;
        }

        public Criteria andJobRunTimeNotIn(List<Long> values) {
            addCriterion("JOB_RUN_TIME not in", values, "jobRunTime");
            return (Criteria) this;
        }

        public Criteria andJobRunTimeBetween(Long value1, Long value2) {
            addCriterion("JOB_RUN_TIME between", value1, value2, "jobRunTime");
            return (Criteria) this;
        }

        public Criteria andJobRunTimeNotBetween(Long value1, Long value2) {
            addCriterion("JOB_RUN_TIME not between", value1, value2, "jobRunTime");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("STATUS is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("STATUS =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("STATUS <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("STATUS >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("STATUS >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("STATUS <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("STATUS <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("STATUS like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("STATUS not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("STATUS in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("STATUS not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("STATUS between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("STATUS not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andResultIsNull() {
            addCriterion("RESULT is null");
            return (Criteria) this;
        }

        public Criteria andResultIsNotNull() {
            addCriterion("RESULT is not null");
            return (Criteria) this;
        }

        public Criteria andResultEqualTo(String value) {
            addCriterion("RESULT =", value, "result");
            return (Criteria) this;
        }

        public Criteria andResultNotEqualTo(String value) {
            addCriterion("RESULT <>", value, "result");
            return (Criteria) this;
        }

        public Criteria andResultGreaterThan(String value) {
            addCriterion("RESULT >", value, "result");
            return (Criteria) this;
        }

        public Criteria andResultGreaterThanOrEqualTo(String value) {
            addCriterion("RESULT >=", value, "result");
            return (Criteria) this;
        }

        public Criteria andResultLessThan(String value) {
            addCriterion("RESULT <", value, "result");
            return (Criteria) this;
        }

        public Criteria andResultLessThanOrEqualTo(String value) {
            addCriterion("RESULT <=", value, "result");
            return (Criteria) this;
        }

        public Criteria andResultLike(String value) {
            addCriterion("RESULT like", value, "result");
            return (Criteria) this;
        }

        public Criteria andResultNotLike(String value) {
            addCriterion("RESULT not like", value, "result");
            return (Criteria) this;
        }

        public Criteria andResultIn(List<String> values) {
            addCriterion("RESULT in", values, "result");
            return (Criteria) this;
        }

        public Criteria andResultNotIn(List<String> values) {
            addCriterion("RESULT not in", values, "result");
            return (Criteria) this;
        }

        public Criteria andResultBetween(String value1, String value2) {
            addCriterion("RESULT between", value1, value2, "result");
            return (Criteria) this;
        }

        public Criteria andResultNotBetween(String value1, String value2) {
            addCriterion("RESULT not between", value1, value2, "result");
            return (Criteria) this;
        }

        public Criteria andErrorMsgIsNull() {
            addCriterion("ERROR_MSG is null");
            return (Criteria) this;
        }

        public Criteria andErrorMsgIsNotNull() {
            addCriterion("ERROR_MSG is not null");
            return (Criteria) this;
        }

        public Criteria andErrorMsgEqualTo(String value) {
            addCriterion("ERROR_MSG =", value, "errorMsg");
            return (Criteria) this;
        }

        public Criteria andErrorMsgNotEqualTo(String value) {
            addCriterion("ERROR_MSG <>", value, "errorMsg");
            return (Criteria) this;
        }

        public Criteria andErrorMsgGreaterThan(String value) {
            addCriterion("ERROR_MSG >", value, "errorMsg");
            return (Criteria) this;
        }

        public Criteria andErrorMsgGreaterThanOrEqualTo(String value) {
            addCriterion("ERROR_MSG >=", value, "errorMsg");
            return (Criteria) this;
        }

        public Criteria andErrorMsgLessThan(String value) {
            addCriterion("ERROR_MSG <", value, "errorMsg");
            return (Criteria) this;
        }

        public Criteria andErrorMsgLessThanOrEqualTo(String value) {
            addCriterion("ERROR_MSG <=", value, "errorMsg");
            return (Criteria) this;
        }

        public Criteria andErrorMsgLike(String value) {
            addCriterion("ERROR_MSG like", value, "errorMsg");
            return (Criteria) this;
        }

        public Criteria andErrorMsgNotLike(String value) {
            addCriterion("ERROR_MSG not like", value, "errorMsg");
            return (Criteria) this;
        }

        public Criteria andErrorMsgIn(List<String> values) {
            addCriterion("ERROR_MSG in", values, "errorMsg");
            return (Criteria) this;
        }

        public Criteria andErrorMsgNotIn(List<String> values) {
            addCriterion("ERROR_MSG not in", values, "errorMsg");
            return (Criteria) this;
        }

        public Criteria andErrorMsgBetween(String value1, String value2) {
            addCriterion("ERROR_MSG between", value1, value2, "errorMsg");
            return (Criteria) this;
        }

        public Criteria andErrorMsgNotBetween(String value1, String value2) {
            addCriterion("ERROR_MSG not between", value1, value2, "errorMsg");
            return (Criteria) this;
        }

        public Criteria andTriggerNameIsNull() {
            addCriterion("TRIGGER_NAME is null");
            return (Criteria) this;
        }

        public Criteria andTriggerNameIsNotNull() {
            addCriterion("TRIGGER_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andTriggerNameEqualTo(String value) {
            addCriterion("TRIGGER_NAME =", value, "triggerName");
            return (Criteria) this;
        }

        public Criteria andTriggerNameNotEqualTo(String value) {
            addCriterion("TRIGGER_NAME <>", value, "triggerName");
            return (Criteria) this;
        }

        public Criteria andTriggerNameGreaterThan(String value) {
            addCriterion("TRIGGER_NAME >", value, "triggerName");
            return (Criteria) this;
        }

        public Criteria andTriggerNameGreaterThanOrEqualTo(String value) {
            addCriterion("TRIGGER_NAME >=", value, "triggerName");
            return (Criteria) this;
        }

        public Criteria andTriggerNameLessThan(String value) {
            addCriterion("TRIGGER_NAME <", value, "triggerName");
            return (Criteria) this;
        }

        public Criteria andTriggerNameLessThanOrEqualTo(String value) {
            addCriterion("TRIGGER_NAME <=", value, "triggerName");
            return (Criteria) this;
        }

        public Criteria andTriggerNameLike(String value) {
            addCriterion("TRIGGER_NAME like", value, "triggerName");
            return (Criteria) this;
        }

        public Criteria andTriggerNameNotLike(String value) {
            addCriterion("TRIGGER_NAME not like", value, "triggerName");
            return (Criteria) this;
        }

        public Criteria andTriggerNameIn(List<String> values) {
            addCriterion("TRIGGER_NAME in", values, "triggerName");
            return (Criteria) this;
        }

        public Criteria andTriggerNameNotIn(List<String> values) {
            addCriterion("TRIGGER_NAME not in", values, "triggerName");
            return (Criteria) this;
        }

        public Criteria andTriggerNameBetween(String value1, String value2) {
            addCriterion("TRIGGER_NAME between", value1, value2, "triggerName");
            return (Criteria) this;
        }

        public Criteria andTriggerNameNotBetween(String value1, String value2) {
            addCriterion("TRIGGER_NAME not between", value1, value2, "triggerName");
            return (Criteria) this;
        }

        public Criteria andTriggerGroupIsNull() {
            addCriterion("TRIGGER_GROUP is null");
            return (Criteria) this;
        }

        public Criteria andTriggerGroupIsNotNull() {
            addCriterion("TRIGGER_GROUP is not null");
            return (Criteria) this;
        }

        public Criteria andTriggerGroupEqualTo(String value) {
            addCriterion("TRIGGER_GROUP =", value, "triggerGroup");
            return (Criteria) this;
        }

        public Criteria andTriggerGroupNotEqualTo(String value) {
            addCriterion("TRIGGER_GROUP <>", value, "triggerGroup");
            return (Criteria) this;
        }

        public Criteria andTriggerGroupGreaterThan(String value) {
            addCriterion("TRIGGER_GROUP >", value, "triggerGroup");
            return (Criteria) this;
        }

        public Criteria andTriggerGroupGreaterThanOrEqualTo(String value) {
            addCriterion("TRIGGER_GROUP >=", value, "triggerGroup");
            return (Criteria) this;
        }

        public Criteria andTriggerGroupLessThan(String value) {
            addCriterion("TRIGGER_GROUP <", value, "triggerGroup");
            return (Criteria) this;
        }

        public Criteria andTriggerGroupLessThanOrEqualTo(String value) {
            addCriterion("TRIGGER_GROUP <=", value, "triggerGroup");
            return (Criteria) this;
        }

        public Criteria andTriggerGroupLike(String value) {
            addCriterion("TRIGGER_GROUP like", value, "triggerGroup");
            return (Criteria) this;
        }

        public Criteria andTriggerGroupNotLike(String value) {
            addCriterion("TRIGGER_GROUP not like", value, "triggerGroup");
            return (Criteria) this;
        }

        public Criteria andTriggerGroupIn(List<String> values) {
            addCriterion("TRIGGER_GROUP in", values, "triggerGroup");
            return (Criteria) this;
        }

        public Criteria andTriggerGroupNotIn(List<String> values) {
            addCriterion("TRIGGER_GROUP not in", values, "triggerGroup");
            return (Criteria) this;
        }

        public Criteria andTriggerGroupBetween(String value1, String value2) {
            addCriterion("TRIGGER_GROUP between", value1, value2, "triggerGroup");
            return (Criteria) this;
        }

        public Criteria andTriggerGroupNotBetween(String value1, String value2) {
            addCriterion("TRIGGER_GROUP not between", value1, value2, "triggerGroup");
            return (Criteria) this;
        }

        public Criteria andJobNameIsNull() {
            addCriterion("JOB_NAME is null");
            return (Criteria) this;
        }

        public Criteria andJobNameIsNotNull() {
            addCriterion("JOB_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andJobNameEqualTo(String value) {
            addCriterion("JOB_NAME =", value, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameNotEqualTo(String value) {
            addCriterion("JOB_NAME <>", value, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameGreaterThan(String value) {
            addCriterion("JOB_NAME >", value, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameGreaterThanOrEqualTo(String value) {
            addCriterion("JOB_NAME >=", value, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameLessThan(String value) {
            addCriterion("JOB_NAME <", value, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameLessThanOrEqualTo(String value) {
            addCriterion("JOB_NAME <=", value, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameLike(String value) {
            addCriterion("JOB_NAME like", value, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameNotLike(String value) {
            addCriterion("JOB_NAME not like", value, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameIn(List<String> values) {
            addCriterion("JOB_NAME in", values, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameNotIn(List<String> values) {
            addCriterion("JOB_NAME not in", values, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameBetween(String value1, String value2) {
            addCriterion("JOB_NAME between", value1, value2, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameNotBetween(String value1, String value2) {
            addCriterion("JOB_NAME not between", value1, value2, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobGroupIsNull() {
            addCriterion("JOB_GROUP is null");
            return (Criteria) this;
        }

        public Criteria andJobGroupIsNotNull() {
            addCriterion("JOB_GROUP is not null");
            return (Criteria) this;
        }

        public Criteria andJobGroupEqualTo(String value) {
            addCriterion("JOB_GROUP =", value, "jobGroup");
            return (Criteria) this;
        }

        public Criteria andJobGroupNotEqualTo(String value) {
            addCriterion("JOB_GROUP <>", value, "jobGroup");
            return (Criteria) this;
        }

        public Criteria andJobGroupGreaterThan(String value) {
            addCriterion("JOB_GROUP >", value, "jobGroup");
            return (Criteria) this;
        }

        public Criteria andJobGroupGreaterThanOrEqualTo(String value) {
            addCriterion("JOB_GROUP >=", value, "jobGroup");
            return (Criteria) this;
        }

        public Criteria andJobGroupLessThan(String value) {
            addCriterion("JOB_GROUP <", value, "jobGroup");
            return (Criteria) this;
        }

        public Criteria andJobGroupLessThanOrEqualTo(String value) {
            addCriterion("JOB_GROUP <=", value, "jobGroup");
            return (Criteria) this;
        }

        public Criteria andJobGroupLike(String value) {
            addCriterion("JOB_GROUP like", value, "jobGroup");
            return (Criteria) this;
        }

        public Criteria andJobGroupNotLike(String value) {
            addCriterion("JOB_GROUP not like", value, "jobGroup");
            return (Criteria) this;
        }

        public Criteria andJobGroupIn(List<String> values) {
            addCriterion("JOB_GROUP in", values, "jobGroup");
            return (Criteria) this;
        }

        public Criteria andJobGroupNotIn(List<String> values) {
            addCriterion("JOB_GROUP not in", values, "jobGroup");
            return (Criteria) this;
        }

        public Criteria andJobGroupBetween(String value1, String value2) {
            addCriterion("JOB_GROUP between", value1, value2, "jobGroup");
            return (Criteria) this;
        }

        public Criteria andJobGroupNotBetween(String value1, String value2) {
            addCriterion("JOB_GROUP not between", value1, value2, "jobGroup");
            return (Criteria) this;
        }

        public Criteria andJobClassIsNull() {
            addCriterion("JOB_CLASS is null");
            return (Criteria) this;
        }

        public Criteria andJobClassIsNotNull() {
            addCriterion("JOB_CLASS is not null");
            return (Criteria) this;
        }

        public Criteria andJobClassEqualTo(String value) {
            addCriterion("JOB_CLASS =", value, "jobClass");
            return (Criteria) this;
        }

        public Criteria andJobClassNotEqualTo(String value) {
            addCriterion("JOB_CLASS <>", value, "jobClass");
            return (Criteria) this;
        }

        public Criteria andJobClassGreaterThan(String value) {
            addCriterion("JOB_CLASS >", value, "jobClass");
            return (Criteria) this;
        }

        public Criteria andJobClassGreaterThanOrEqualTo(String value) {
            addCriterion("JOB_CLASS >=", value, "jobClass");
            return (Criteria) this;
        }

        public Criteria andJobClassLessThan(String value) {
            addCriterion("JOB_CLASS <", value, "jobClass");
            return (Criteria) this;
        }

        public Criteria andJobClassLessThanOrEqualTo(String value) {
            addCriterion("JOB_CLASS <=", value, "jobClass");
            return (Criteria) this;
        }

        public Criteria andJobClassLike(String value) {
            addCriterion("JOB_CLASS like", value, "jobClass");
            return (Criteria) this;
        }

        public Criteria andJobClassNotLike(String value) {
            addCriterion("JOB_CLASS not like", value, "jobClass");
            return (Criteria) this;
        }

        public Criteria andJobClassIn(List<String> values) {
            addCriterion("JOB_CLASS in", values, "jobClass");
            return (Criteria) this;
        }

        public Criteria andJobClassNotIn(List<String> values) {
            addCriterion("JOB_CLASS not in", values, "jobClass");
            return (Criteria) this;
        }

        public Criteria andJobClassBetween(String value1, String value2) {
            addCriterion("JOB_CLASS between", value1, value2, "jobClass");
            return (Criteria) this;
        }

        public Criteria andJobClassNotBetween(String value1, String value2) {
            addCriterion("JOB_CLASS not between", value1, value2, "jobClass");
            return (Criteria) this;
        }

        public Criteria andThreadGroupNameIsNull() {
            addCriterion("THREAD_GROUP_NAME is null");
            return (Criteria) this;
        }

        public Criteria andThreadGroupNameIsNotNull() {
            addCriterion("THREAD_GROUP_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andThreadGroupNameEqualTo(String value) {
            addCriterion("THREAD_GROUP_NAME =", value, "threadGroupName");
            return (Criteria) this;
        }

        public Criteria andThreadGroupNameNotEqualTo(String value) {
            addCriterion("THREAD_GROUP_NAME <>", value, "threadGroupName");
            return (Criteria) this;
        }

        public Criteria andThreadGroupNameGreaterThan(String value) {
            addCriterion("THREAD_GROUP_NAME >", value, "threadGroupName");
            return (Criteria) this;
        }

        public Criteria andThreadGroupNameGreaterThanOrEqualTo(String value) {
            addCriterion("THREAD_GROUP_NAME >=", value, "threadGroupName");
            return (Criteria) this;
        }

        public Criteria andThreadGroupNameLessThan(String value) {
            addCriterion("THREAD_GROUP_NAME <", value, "threadGroupName");
            return (Criteria) this;
        }

        public Criteria andThreadGroupNameLessThanOrEqualTo(String value) {
            addCriterion("THREAD_GROUP_NAME <=", value, "threadGroupName");
            return (Criteria) this;
        }

        public Criteria andThreadGroupNameLike(String value) {
            addCriterion("THREAD_GROUP_NAME like", value, "threadGroupName");
            return (Criteria) this;
        }

        public Criteria andThreadGroupNameNotLike(String value) {
            addCriterion("THREAD_GROUP_NAME not like", value, "threadGroupName");
            return (Criteria) this;
        }

        public Criteria andThreadGroupNameIn(List<String> values) {
            addCriterion("THREAD_GROUP_NAME in", values, "threadGroupName");
            return (Criteria) this;
        }

        public Criteria andThreadGroupNameNotIn(List<String> values) {
            addCriterion("THREAD_GROUP_NAME not in", values, "threadGroupName");
            return (Criteria) this;
        }

        public Criteria andThreadGroupNameBetween(String value1, String value2) {
            addCriterion("THREAD_GROUP_NAME between", value1, value2, "threadGroupName");
            return (Criteria) this;
        }

        public Criteria andThreadGroupNameNotBetween(String value1, String value2) {
            addCriterion("THREAD_GROUP_NAME not between", value1, value2, "threadGroupName");
            return (Criteria) this;
        }

        public Criteria andThreadIdIsNull() {
            addCriterion("THREAD_ID is null");
            return (Criteria) this;
        }

        public Criteria andThreadIdIsNotNull() {
            addCriterion("THREAD_ID is not null");
            return (Criteria) this;
        }

        public Criteria andThreadIdEqualTo(String value) {
            addCriterion("THREAD_ID =", value, "threadId");
            return (Criteria) this;
        }

        public Criteria andThreadIdNotEqualTo(String value) {
            addCriterion("THREAD_ID <>", value, "threadId");
            return (Criteria) this;
        }

        public Criteria andThreadIdGreaterThan(String value) {
            addCriterion("THREAD_ID >", value, "threadId");
            return (Criteria) this;
        }

        public Criteria andThreadIdGreaterThanOrEqualTo(String value) {
            addCriterion("THREAD_ID >=", value, "threadId");
            return (Criteria) this;
        }

        public Criteria andThreadIdLessThan(String value) {
            addCriterion("THREAD_ID <", value, "threadId");
            return (Criteria) this;
        }

        public Criteria andThreadIdLessThanOrEqualTo(String value) {
            addCriterion("THREAD_ID <=", value, "threadId");
            return (Criteria) this;
        }

        public Criteria andThreadIdLike(String value) {
            addCriterion("THREAD_ID like", value, "threadId");
            return (Criteria) this;
        }

        public Criteria andThreadIdNotLike(String value) {
            addCriterion("THREAD_ID not like", value, "threadId");
            return (Criteria) this;
        }

        public Criteria andThreadIdIn(List<String> values) {
            addCriterion("THREAD_ID in", values, "threadId");
            return (Criteria) this;
        }

        public Criteria andThreadIdNotIn(List<String> values) {
            addCriterion("THREAD_ID not in", values, "threadId");
            return (Criteria) this;
        }

        public Criteria andThreadIdBetween(String value1, String value2) {
            addCriterion("THREAD_ID between", value1, value2, "threadId");
            return (Criteria) this;
        }

        public Criteria andThreadIdNotBetween(String value1, String value2) {
            addCriterion("THREAD_ID not between", value1, value2, "threadId");
            return (Criteria) this;
        }

        public Criteria andThreadNameIsNull() {
            addCriterion("THREAD_NAME is null");
            return (Criteria) this;
        }

        public Criteria andThreadNameIsNotNull() {
            addCriterion("THREAD_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andThreadNameEqualTo(String value) {
            addCriterion("THREAD_NAME =", value, "threadName");
            return (Criteria) this;
        }

        public Criteria andThreadNameNotEqualTo(String value) {
            addCriterion("THREAD_NAME <>", value, "threadName");
            return (Criteria) this;
        }

        public Criteria andThreadNameGreaterThan(String value) {
            addCriterion("THREAD_NAME >", value, "threadName");
            return (Criteria) this;
        }

        public Criteria andThreadNameGreaterThanOrEqualTo(String value) {
            addCriterion("THREAD_NAME >=", value, "threadName");
            return (Criteria) this;
        }

        public Criteria andThreadNameLessThan(String value) {
            addCriterion("THREAD_NAME <", value, "threadName");
            return (Criteria) this;
        }

        public Criteria andThreadNameLessThanOrEqualTo(String value) {
            addCriterion("THREAD_NAME <=", value, "threadName");
            return (Criteria) this;
        }

        public Criteria andThreadNameLike(String value) {
            addCriterion("THREAD_NAME like", value, "threadName");
            return (Criteria) this;
        }

        public Criteria andThreadNameNotLike(String value) {
            addCriterion("THREAD_NAME not like", value, "threadName");
            return (Criteria) this;
        }

        public Criteria andThreadNameIn(List<String> values) {
            addCriterion("THREAD_NAME in", values, "threadName");
            return (Criteria) this;
        }

        public Criteria andThreadNameNotIn(List<String> values) {
            addCriterion("THREAD_NAME not in", values, "threadName");
            return (Criteria) this;
        }

        public Criteria andThreadNameBetween(String value1, String value2) {
            addCriterion("THREAD_NAME between", value1, value2, "threadName");
            return (Criteria) this;
        }

        public Criteria andThreadNameNotBetween(String value1, String value2) {
            addCriterion("THREAD_NAME not between", value1, value2, "threadName");
            return (Criteria) this;
        }

        public Criteria andThreadPriorityIsNull() {
            addCriterion("THREAD_PRIORITY is null");
            return (Criteria) this;
        }

        public Criteria andThreadPriorityIsNotNull() {
            addCriterion("THREAD_PRIORITY is not null");
            return (Criteria) this;
        }

        public Criteria andThreadPriorityEqualTo(String value) {
            addCriterion("THREAD_PRIORITY =", value, "threadPriority");
            return (Criteria) this;
        }

        public Criteria andThreadPriorityNotEqualTo(String value) {
            addCriterion("THREAD_PRIORITY <>", value, "threadPriority");
            return (Criteria) this;
        }

        public Criteria andThreadPriorityGreaterThan(String value) {
            addCriterion("THREAD_PRIORITY >", value, "threadPriority");
            return (Criteria) this;
        }

        public Criteria andThreadPriorityGreaterThanOrEqualTo(String value) {
            addCriterion("THREAD_PRIORITY >=", value, "threadPriority");
            return (Criteria) this;
        }

        public Criteria andThreadPriorityLessThan(String value) {
            addCriterion("THREAD_PRIORITY <", value, "threadPriority");
            return (Criteria) this;
        }

        public Criteria andThreadPriorityLessThanOrEqualTo(String value) {
            addCriterion("THREAD_PRIORITY <=", value, "threadPriority");
            return (Criteria) this;
        }

        public Criteria andThreadPriorityLike(String value) {
            addCriterion("THREAD_PRIORITY like", value, "threadPriority");
            return (Criteria) this;
        }

        public Criteria andThreadPriorityNotLike(String value) {
            addCriterion("THREAD_PRIORITY not like", value, "threadPriority");
            return (Criteria) this;
        }

        public Criteria andThreadPriorityIn(List<String> values) {
            addCriterion("THREAD_PRIORITY in", values, "threadPriority");
            return (Criteria) this;
        }

        public Criteria andThreadPriorityNotIn(List<String> values) {
            addCriterion("THREAD_PRIORITY not in", values, "threadPriority");
            return (Criteria) this;
        }

        public Criteria andThreadPriorityBetween(String value1, String value2) {
            addCriterion("THREAD_PRIORITY between", value1, value2, "threadPriority");
            return (Criteria) this;
        }

        public Criteria andThreadPriorityNotBetween(String value1, String value2) {
            addCriterion("THREAD_PRIORITY not between", value1, value2, "threadPriority");
            return (Criteria) this;
        }

        public Criteria andScheduledIdIsNull() {
            addCriterion("SCHEDULED_ID is null");
            return (Criteria) this;
        }

        public Criteria andScheduledIdIsNotNull() {
            addCriterion("SCHEDULED_ID is not null");
            return (Criteria) this;
        }

        public Criteria andScheduledIdEqualTo(String value) {
            addCriterion("SCHEDULED_ID =", value, "scheduledId");
            return (Criteria) this;
        }

        public Criteria andScheduledIdNotEqualTo(String value) {
            addCriterion("SCHEDULED_ID <>", value, "scheduledId");
            return (Criteria) this;
        }

        public Criteria andScheduledIdGreaterThan(String value) {
            addCriterion("SCHEDULED_ID >", value, "scheduledId");
            return (Criteria) this;
        }

        public Criteria andScheduledIdGreaterThanOrEqualTo(String value) {
            addCriterion("SCHEDULED_ID >=", value, "scheduledId");
            return (Criteria) this;
        }

        public Criteria andScheduledIdLessThan(String value) {
            addCriterion("SCHEDULED_ID <", value, "scheduledId");
            return (Criteria) this;
        }

        public Criteria andScheduledIdLessThanOrEqualTo(String value) {
            addCriterion("SCHEDULED_ID <=", value, "scheduledId");
            return (Criteria) this;
        }

        public Criteria andScheduledIdLike(String value) {
            addCriterion("SCHEDULED_ID like", value, "scheduledId");
            return (Criteria) this;
        }

        public Criteria andScheduledIdNotLike(String value) {
            addCriterion("SCHEDULED_ID not like", value, "scheduledId");
            return (Criteria) this;
        }

        public Criteria andScheduledIdIn(List<String> values) {
            addCriterion("SCHEDULED_ID in", values, "scheduledId");
            return (Criteria) this;
        }

        public Criteria andScheduledIdNotIn(List<String> values) {
            addCriterion("SCHEDULED_ID not in", values, "scheduledId");
            return (Criteria) this;
        }

        public Criteria andScheduledIdBetween(String value1, String value2) {
            addCriterion("SCHEDULED_ID between", value1, value2, "scheduledId");
            return (Criteria) this;
        }

        public Criteria andScheduledIdNotBetween(String value1, String value2) {
            addCriterion("SCHEDULED_ID not between", value1, value2, "scheduledId");
            return (Criteria) this;
        }

        public Criteria andScheduledNameIsNull() {
            addCriterion("SCHEDULED_NAME is null");
            return (Criteria) this;
        }

        public Criteria andScheduledNameIsNotNull() {
            addCriterion("SCHEDULED_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andScheduledNameEqualTo(String value) {
            addCriterion("SCHEDULED_NAME =", value, "scheduledName");
            return (Criteria) this;
        }

        public Criteria andScheduledNameNotEqualTo(String value) {
            addCriterion("SCHEDULED_NAME <>", value, "scheduledName");
            return (Criteria) this;
        }

        public Criteria andScheduledNameGreaterThan(String value) {
            addCriterion("SCHEDULED_NAME >", value, "scheduledName");
            return (Criteria) this;
        }

        public Criteria andScheduledNameGreaterThanOrEqualTo(String value) {
            addCriterion("SCHEDULED_NAME >=", value, "scheduledName");
            return (Criteria) this;
        }

        public Criteria andScheduledNameLessThan(String value) {
            addCriterion("SCHEDULED_NAME <", value, "scheduledName");
            return (Criteria) this;
        }

        public Criteria andScheduledNameLessThanOrEqualTo(String value) {
            addCriterion("SCHEDULED_NAME <=", value, "scheduledName");
            return (Criteria) this;
        }

        public Criteria andScheduledNameLike(String value) {
            addCriterion("SCHEDULED_NAME like", value, "scheduledName");
            return (Criteria) this;
        }

        public Criteria andScheduledNameNotLike(String value) {
            addCriterion("SCHEDULED_NAME not like", value, "scheduledName");
            return (Criteria) this;
        }

        public Criteria andScheduledNameIn(List<String> values) {
            addCriterion("SCHEDULED_NAME in", values, "scheduledName");
            return (Criteria) this;
        }

        public Criteria andScheduledNameNotIn(List<String> values) {
            addCriterion("SCHEDULED_NAME not in", values, "scheduledName");
            return (Criteria) this;
        }

        public Criteria andScheduledNameBetween(String value1, String value2) {
            addCriterion("SCHEDULED_NAME between", value1, value2, "scheduledName");
            return (Criteria) this;
        }

        public Criteria andScheduledNameNotBetween(String value1, String value2) {
            addCriterion("SCHEDULED_NAME not between", value1, value2, "scheduledName");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("CREATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("CREATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("CREATE_DATE =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("CREATE_DATE <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("CREATE_DATE >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_DATE >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("CREATE_DATE <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_DATE <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("CREATE_DATE in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("CREATE_DATE not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("CREATE_DATE between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_DATE not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andLogidLikeInsensitive(String value) {
            addCriterion("upper(LOGID) like", value.toUpperCase(), "logid");
            return (Criteria) this;
        }

        public Criteria andStatusLikeInsensitive(String value) {
            addCriterion("upper(STATUS) like", value.toUpperCase(), "status");
            return (Criteria) this;
        }

        public Criteria andResultLikeInsensitive(String value) {
            addCriterion("upper(RESULT) like", value.toUpperCase(), "result");
            return (Criteria) this;
        }

        public Criteria andErrorMsgLikeInsensitive(String value) {
            addCriterion("upper(ERROR_MSG) like", value.toUpperCase(), "errorMsg");
            return (Criteria) this;
        }

        public Criteria andTriggerNameLikeInsensitive(String value) {
            addCriterion("upper(TRIGGER_NAME) like", value.toUpperCase(), "triggerName");
            return (Criteria) this;
        }

        public Criteria andTriggerGroupLikeInsensitive(String value) {
            addCriterion("upper(TRIGGER_GROUP) like", value.toUpperCase(), "triggerGroup");
            return (Criteria) this;
        }

        public Criteria andJobNameLikeInsensitive(String value) {
            addCriterion("upper(JOB_NAME) like", value.toUpperCase(), "jobName");
            return (Criteria) this;
        }

        public Criteria andJobGroupLikeInsensitive(String value) {
            addCriterion("upper(JOB_GROUP) like", value.toUpperCase(), "jobGroup");
            return (Criteria) this;
        }

        public Criteria andJobClassLikeInsensitive(String value) {
            addCriterion("upper(JOB_CLASS) like", value.toUpperCase(), "jobClass");
            return (Criteria) this;
        }

        public Criteria andThreadGroupNameLikeInsensitive(String value) {
            addCriterion("upper(THREAD_GROUP_NAME) like", value.toUpperCase(), "threadGroupName");
            return (Criteria) this;
        }

        public Criteria andThreadIdLikeInsensitive(String value) {
            addCriterion("upper(THREAD_ID) like", value.toUpperCase(), "threadId");
            return (Criteria) this;
        }

        public Criteria andThreadNameLikeInsensitive(String value) {
            addCriterion("upper(THREAD_NAME) like", value.toUpperCase(), "threadName");
            return (Criteria) this;
        }

        public Criteria andThreadPriorityLikeInsensitive(String value) {
            addCriterion("upper(THREAD_PRIORITY) like", value.toUpperCase(), "threadPriority");
            return (Criteria) this;
        }

        public Criteria andScheduledIdLikeInsensitive(String value) {
            addCriterion("upper(SCHEDULED_ID) like", value.toUpperCase(), "scheduledId");
            return (Criteria) this;
        }

        public Criteria andScheduledNameLikeInsensitive(String value) {
            addCriterion("upper(SCHEDULED_NAME) like", value.toUpperCase(), "scheduledName");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TT_SCHEDULED_TRIGGER_LOG
     *
     * @mbggenerated do_not_delete_during_merge Mon May 05 11:25:40 CST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TT_SCHEDULED_TRIGGER_LOG
     *
     * @mbggenerated Mon May 05 11:25:40 CST 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}