Insert into TT_ORGANIZATION
   (ORG_CODE, ORG_NAME, PARENT_ORG_CODE, ORG_SORT, CREATE_BY, 
    CREATE_DATE)
 Values
   ('TEST_BM', '测试部门', 'TEST_COMPY', '1', 'admin', 
    TO_DATE('05/03/2014 10:16:24', 'MM/DD/YYYY HH24:MI:SS'));
Insert into TT_ORGANIZATION
   (ORG_CODE, ORG_NAME, ORG_SORT, CREATE_BY, CREATE_DATE)
 Values
   ('ORG_ADMIN', '系统管理部', '1', 'admin', TO_DATE('05/03/2014 11:59:20', 'MM/DD/YYYY HH24:MI:SS'));
Insert into TT_ORGANIZATION
   (ORG_CODE, ORG_NAME, PARENT_ORG_CODE, ORG_SORT, CREATE_BY, 
    CREATE_DATE, UPDATE_BY, UPDATE_DATE)
 Values
   ('TEST_Z2', '测试项目组2', 'TEST_BM', '2', 'admin', 
    TO_DATE('05/03/2014 10:16:56', 'MM/DD/YYYY HH24:MI:SS'), 'admin', TO_DATE('05/03/2014 10:17:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into TT_ORGANIZATION
   (ORG_CODE, ORG_NAME, PARENT_ORG_CODE, ORG_SORT, CREATE_BY, 
    CREATE_DATE, UPDATE_BY, UPDATE_DATE)
 Values
   ('TEST_Z1', '测试项目组1', 'TEST_BM', '1', 'admin', 
    TO_DATE('05/03/2014 11:58:20', 'MM/DD/YYYY HH24:MI:SS'), 'admin', TO_DATE('05/03/2014 11:58:29', 'MM/DD/YYYY HH24:MI:SS'));
Insert into TT_ORGANIZATION
   (ORG_CODE, ORG_NAME, ORG_SORT, CREATE_BY, CREATE_DATE)
 Values
   ('TEST_COMPY', '测试公司', '1', 'admin', TO_DATE('05/02/2014 20:35:12', 'MM/DD/YYYY HH24:MI:SS'));
COMMIT;
