Insert into TT_FUNCTION
   (FUNCTION_CODE, FUNCTION_NAME, STATUS, PARENT_FUNCTION_CODE, SORT, 
    LEVEL_NO, REQUEST_URL, CREATE_BY, CREATE_DATE, UPDATE_BY, 
    UPDATE_DATE)
 Values
   ('roleController', '角色维护', '1', 'PURVIEW_SETTING_MENU', 3, 
    3, 'roleController/init', 'admin', TO_DATE('04/25/2014 16:49:01', 'MM/DD/YYYY HH24:MI:SS'), 'admin', 
    TO_DATE('05/08/2014 14:06:59', 'MM/DD/YYYY HH24:MI:SS'));
Insert into TT_FUNCTION
   (FUNCTION_CODE, FUNCTION_NAME, STATUS, PARENT_FUNCTION_CODE, SORT, 
    LEVEL_NO, REQUEST_URL, CREATE_BY, CREATE_DATE, UPDATE_BY, 
    UPDATE_DATE)
 Values
   ('testController', '测试功能', '1', 'TEST_MENU', 1, 
    3, 'testController/init', 'admin', TO_DATE('03/11/2014 14:25:09', 'MM/DD/YYYY HH24:MI:SS'), 'admin', 
    TO_DATE('05/02/2014 16:38:26', 'MM/DD/YYYY HH24:MI:SS'));
Insert into TT_FUNCTION
   (FUNCTION_CODE, FUNCTION_NAME, STATUS, SORT, LEVEL_NO, 
    CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE)
 Values
   ('SYSTEM_APP', '系统管理', '1', 1, 1, 
    'admin', TO_DATE('12/16/2013 16:50:54', 'MM/DD/YYYY HH24:MI:SS'), 'admin', TO_DATE('05/02/2014 16:44:08', 'MM/DD/YYYY HH24:MI:SS'));
Insert into TT_FUNCTION
   (FUNCTION_CODE, FUNCTION_NAME, STATUS, PARENT_FUNCTION_CODE, SORT, 
    LEVEL_NO, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE)
 Values
   ('TEST_MENU', '测试目录', '1', 'BFTS_APP', 1, 
    2, 'admin', TO_DATE('12/16/2013 16:53:24', 'MM/DD/YYYY HH24:MI:SS'), 'admin', TO_DATE('05/02/2014 16:44:41', 'MM/DD/YYYY HH24:MI:SS'));
Insert into TT_FUNCTION
   (FUNCTION_CODE, FUNCTION_NAME, STATUS, PARENT_FUNCTION_CODE, SORT, 
    LEVEL_NO, REQUEST_URL, CREATE_BY, CREATE_DATE, UPDATE_BY, 
    UPDATE_DATE)
 Values
   ('quartzController', '定时任务管理', '1', 'SYSTEM_SETTING_MENU', 2, 
    3, 'quartzController/init', 'admin', TO_DATE('12/20/2013 21:48:23', 'MM/DD/YYYY HH24:MI:SS'), 'admin', 
    TO_DATE('03/11/2014 14:24:32', 'MM/DD/YYYY HH24:MI:SS'));
Insert into TT_FUNCTION
   (FUNCTION_CODE, FUNCTION_NAME, STATUS, PARENT_FUNCTION_CODE, SORT, 
    LEVEL_NO, REQUEST_URL, CREATE_BY, CREATE_DATE, UPDATE_BY, 
    UPDATE_DATE)
 Values
   ('userController', '用户维护', '1', 'PURVIEW_SETTING_MENU', 1, 
    3, 'userController/init', 'SYSTEM', TO_DATE('12/15/2013 15:40:20', 'MM/DD/YYYY HH24:MI:SS'), 'admin', 
    TO_DATE('05/02/2014 16:44:29', 'MM/DD/YYYY HH24:MI:SS'));
Insert into TT_FUNCTION
   (FUNCTION_CODE, FUNCTION_NAME, STATUS, PARENT_FUNCTION_CODE, SORT, 
    LEVEL_NO, REQUEST_URL, CREATE_BY, CREATE_DATE, UPDATE_BY, 
    UPDATE_DATE)
 Values
   ('orgController', '组织维护', '1', 'PURVIEW_SETTING_MENU', 2, 
    3, 'orgController/init', 'admin', TO_DATE('05/02/2014 16:48:46', 'MM/DD/YYYY HH24:MI:SS'), 'admin', 
    TO_DATE('05/08/2014 14:06:35', 'MM/DD/YYYY HH24:MI:SS'));
Insert into TT_FUNCTION
   (FUNCTION_CODE, FUNCTION_NAME, STATUS, SORT, LEVEL_NO, 
    CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE)
 Values
   ('BFTS_APP', '测试系统模块', '1', 2, 1, 
    'SYSTEM', TO_DATE('12/08/2013 13:01:45', 'MM/DD/YYYY HH24:MI:SS'), 'admin', TO_DATE('04/25/2014 16:44:59', 'MM/DD/YYYY HH24:MI:SS'));
Insert into TT_FUNCTION
   (FUNCTION_CODE, FUNCTION_NAME, STATUS, PARENT_FUNCTION_CODE, SORT, 
    LEVEL_NO, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE)
 Values
   ('SYSTEM_SETTING_MENU', '系统设置', '1', 'SYSTEM_APP', 2, 
    2, 'SYSTEM', TO_DATE('12/08/2013 13:02:17', 'MM/DD/YYYY HH24:MI:SS'), 'admin', TO_DATE('05/02/2014 16:44:57', 'MM/DD/YYYY HH24:MI:SS'));
Insert into TT_FUNCTION
   (FUNCTION_CODE, FUNCTION_NAME, STATUS, PARENT_FUNCTION_CODE, SORT, 
    LEVEL_NO, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE)
 Values
   ('PURVIEW_SETTING_MENU', '权限设置', '1', 'SYSTEM_APP', 1, 
    2, 'SYSTEM', TO_DATE('12/08/2013 13:03:14', 'MM/DD/YYYY HH24:MI:SS'), 'admin', TO_DATE('05/02/2014 16:45:07', 'MM/DD/YYYY HH24:MI:SS'));
Insert into TT_FUNCTION
   (FUNCTION_CODE, FUNCTION_NAME, STATUS, PARENT_FUNCTION_CODE, SORT, 
    LEVEL_NO, REQUEST_URL, CREATE_BY, CREATE_DATE, UPDATE_BY, 
    UPDATE_DATE)
 Values
   ('serviceParamController', '环境变量设定', '1', 'SYSTEM_SETTING_MENU', 1, 
    3, 'serviceParamController/init', 'SYSTEM', TO_DATE('12/08/2013 13:05:33', 'MM/DD/YYYY HH24:MI:SS'), 'admin', 
    TO_DATE('05/03/2014 14:39:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into TT_FUNCTION
   (FUNCTION_CODE, FUNCTION_NAME, STATUS, PARENT_FUNCTION_CODE, SORT, 
    LEVEL_NO, REQUEST_URL, CREATE_BY, CREATE_DATE, UPDATE_BY, 
    UPDATE_DATE)
 Values
   ('functionController', '功能维护', '1', 'PURVIEW_SETTING_MENU', 4, 
    3, 'functionController/init', 'SYSTEM', TO_DATE('12/08/2013 13:06:15', 'MM/DD/YYYY HH24:MI:SS'), 'admin', 
    TO_DATE('05/08/2014 14:07:03', 'MM/DD/YYYY HH24:MI:SS'));
COMMIT;
