SET DEFINE OFF;
Insert into TT_SERVER_GLOBAL_PARAMETERS
   (PARAMETERS_CODE, PARAMETERS_VALUE, PARAMETERS_DESC, PARAMETERS_TYPE_CODE, PARAMETERS_TYPE_NAME)
 Values
   ('PAGE_SIZE', '100', '分页条数', 'SYSTEM_PARAM', '系统参数');
Insert into TT_SERVER_GLOBAL_PARAMETERS
   (PARAMETERS_CODE, PARAMETERS_VALUE, PARAMETERS_DESC, PARAMETERS_TYPE_CODE, PARAMETERS_TYPE_NAME)
 Values
   ('SYSTEM_DEF_PSWD', '123456', '系统初始化密码', 'SYSTEM_PARAM', '系统参数');
Insert into TT_SERVER_GLOBAL_PARAMETERS
   (PARAMETERS_CODE, PARAMETERS_VALUE, PARAMETERS_DESC, PARAMETERS_TYPE_CODE, PARAMETERS_TYPE_NAME)
 Values
   ('SESSION_NAME', 'USER_SESSION', 'session名称', 'SYSTEM_PARAM', '系统参数');
Insert into TT_SERVER_GLOBAL_PARAMETERS
   (PARAMETERS_CODE, PARAMETERS_VALUE, PARAMETERS_DESC, PARAMETERS_TYPE_CODE, PARAMETERS_TYPE_NAME)
 Values
   ('ADMIN_USER', 'admin', '管理员账户', 'SYSTEM_PARAM', '系统参数');
Insert into TT_SERVER_GLOBAL_PARAMETERS
   (PARAMETERS_CODE, PARAMETERS_VALUE, PARAMETERS_DESC, PARAMETERS_TYPE_CODE, PARAMETERS_TYPE_NAME)
 Values
   ('SYSTEM_DEF_NAME', 'SYSTEM', '系统默认登录名', 'SYSTEM_PARAM', '系统参数');
Insert into TT_SERVER_GLOBAL_PARAMETERS
   (PARAMETERS_CODE, PARAMETERS_VALUE, PARAMETERS_DESC, PARAMETERS_TYPE_CODE, PARAMETERS_TYPE_NAME)
 Values
   ('DETAILED_RECORDS', 'true', '是否记录详细的执行历史', 'SCHEDULER_PARAM', '计划任务');
Insert into TT_SERVER_GLOBAL_PARAMETERS
   (PARAMETERS_CODE, PARAMETERS_VALUE, PARAMETERS_DESC, PARAMETERS_TYPE_CODE, PARAMETERS_TYPE_NAME)
 Values
   ('TRIGGER_SEARCH_INTERVAL', '60000', '触发器轮询间隔(毫秒)', 'SCHEDULER_PARAM', '计划任务');
COMMIT;
