package com.llsfw.core.mapper.standard;

import com.llsfw.core.model.standard.TtUserRole;
import com.llsfw.core.model.standard.TtUserRoleCriteria;
import com.llsfw.core.model.standard.TtUserRoleKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TtUserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_USER_ROLE
     *
     * @mbggenerated Sun Apr 20 00:31:30 CST 2014
     */
    int countByExample(TtUserRoleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_USER_ROLE
     *
     * @mbggenerated Sun Apr 20 00:31:30 CST 2014
     */
    int deleteByExample(TtUserRoleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_USER_ROLE
     *
     * @mbggenerated Sun Apr 20 00:31:30 CST 2014
     */
    int deleteByPrimaryKey(TtUserRoleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_USER_ROLE
     *
     * @mbggenerated Sun Apr 20 00:31:30 CST 2014
     */
    int insert(TtUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_USER_ROLE
     *
     * @mbggenerated Sun Apr 20 00:31:30 CST 2014
     */
    int insertSelective(TtUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_USER_ROLE
     *
     * @mbggenerated Sun Apr 20 00:31:30 CST 2014
     */
    List<TtUserRole> selectByExample(TtUserRoleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_USER_ROLE
     *
     * @mbggenerated Sun Apr 20 00:31:30 CST 2014
     */
    TtUserRole selectByPrimaryKey(TtUserRoleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_USER_ROLE
     *
     * @mbggenerated Sun Apr 20 00:31:30 CST 2014
     */
    int updateByExampleSelective(@Param("record") TtUserRole record, @Param("example") TtUserRoleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_USER_ROLE
     *
     * @mbggenerated Sun Apr 20 00:31:30 CST 2014
     */
    int updateByExample(@Param("record") TtUserRole record, @Param("example") TtUserRoleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_USER_ROLE
     *
     * @mbggenerated Sun Apr 20 00:31:30 CST 2014
     */
    int updateByPrimaryKeySelective(TtUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_USER_ROLE
     *
     * @mbggenerated Sun Apr 20 00:31:30 CST 2014
     */
    int updateByPrimaryKey(TtUserRole record);
}