package com.llsfw.core.model.standard;

import java.io.Serializable;

public class TtJobRoleKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_JOB_ROLE.ROLE_CODE
     *
     * @mbggenerated Mon May 05 17:09:26 CST 2014
     */
    private String roleCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_JOB_ROLE.JOB_CODE
     *
     * @mbggenerated Mon May 05 17:09:26 CST 2014
     */
    private String jobCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TT_JOB_ROLE
     *
     * @mbggenerated Mon May 05 17:09:26 CST 2014
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_JOB_ROLE.ROLE_CODE
     *
     * @return the value of TT_JOB_ROLE.ROLE_CODE
     *
     * @mbggenerated Mon May 05 17:09:26 CST 2014
     */
    public String getRoleCode() {
        return roleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_JOB_ROLE.ROLE_CODE
     *
     * @param roleCode the value for TT_JOB_ROLE.ROLE_CODE
     *
     * @mbggenerated Mon May 05 17:09:26 CST 2014
     */
    public void setRoleCode(String roleCode) {
        this.roleCode = roleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_JOB_ROLE.JOB_CODE
     *
     * @return the value of TT_JOB_ROLE.JOB_CODE
     *
     * @mbggenerated Mon May 05 17:09:26 CST 2014
     */
    public String getJobCode() {
        return jobCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_JOB_ROLE.JOB_CODE
     *
     * @param jobCode the value for TT_JOB_ROLE.JOB_CODE
     *
     * @mbggenerated Mon May 05 17:09:26 CST 2014
     */
    public void setJobCode(String jobCode) {
        this.jobCode = jobCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_JOB_ROLE
     *
     * @mbggenerated Mon May 05 17:09:26 CST 2014
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TtJobRoleKey other = (TtJobRoleKey) that;
        return (this.getRoleCode() == null ? other.getRoleCode() == null : this.getRoleCode().equals(other.getRoleCode()))
            && (this.getJobCode() == null ? other.getJobCode() == null : this.getJobCode().equals(other.getJobCode()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_JOB_ROLE
     *
     * @mbggenerated Mon May 05 17:09:26 CST 2014
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getRoleCode() == null) ? 0 : getRoleCode().hashCode());
        result = prime * result + ((getJobCode() == null) ? 0 : getJobCode().hashCode());
        return result;
    }
}