package com.llsfw.core.model.standard;

import java.io.Serializable;
import java.util.Date;

public class TtRole implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_ROLE.ROLE_CODE
     *
     * @mbggenerated Mon May 05 17:09:26 CST 2014
     */
    private String roleCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_ROLE.ROLE_NAME
     *
     * @mbggenerated Mon May 05 17:09:26 CST 2014
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_ROLE.CREATE_BY
     *
     * @mbggenerated Mon May 05 17:09:26 CST 2014
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_ROLE.CREATE_DATE
     *
     * @mbggenerated Mon May 05 17:09:26 CST 2014
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_ROLE.UPDATE_BY
     *
     * @mbggenerated Mon May 05 17:09:26 CST 2014
     */
    private String updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_ROLE.UPDATE_DATE
     *
     * @mbggenerated Mon May 05 17:09:26 CST 2014
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TT_ROLE
     *
     * @mbggenerated Mon May 05 17:09:26 CST 2014
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_ROLE.ROLE_CODE
     *
     * @return the value of TT_ROLE.ROLE_CODE
     *
     * @mbggenerated Mon May 05 17:09:26 CST 2014
     */
    public String getRoleCode() {
        return roleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_ROLE.ROLE_CODE
     *
     * @param roleCode the value for TT_ROLE.ROLE_CODE
     *
     * @mbggenerated Mon May 05 17:09:26 CST 2014
     */
    public void setRoleCode(String roleCode) {
        this.roleCode = roleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_ROLE.ROLE_NAME
     *
     * @return the value of TT_ROLE.ROLE_NAME
     *
     * @mbggenerated Mon May 05 17:09:26 CST 2014
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_ROLE.ROLE_NAME
     *
     * @param roleName the value for TT_ROLE.ROLE_NAME
     *
     * @mbggenerated Mon May 05 17:09:26 CST 2014
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_ROLE.CREATE_BY
     *
     * @return the value of TT_ROLE.CREATE_BY
     *
     * @mbggenerated Mon May 05 17:09:26 CST 2014
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_ROLE.CREATE_BY
     *
     * @param createBy the value for TT_ROLE.CREATE_BY
     *
     * @mbggenerated Mon May 05 17:09:26 CST 2014
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_ROLE.CREATE_DATE
     *
     * @return the value of TT_ROLE.CREATE_DATE
     *
     * @mbggenerated Mon May 05 17:09:26 CST 2014
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_ROLE.CREATE_DATE
     *
     * @param createDate the value for TT_ROLE.CREATE_DATE
     *
     * @mbggenerated Mon May 05 17:09:26 CST 2014
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_ROLE.UPDATE_BY
     *
     * @return the value of TT_ROLE.UPDATE_BY
     *
     * @mbggenerated Mon May 05 17:09:26 CST 2014
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_ROLE.UPDATE_BY
     *
     * @param updateBy the value for TT_ROLE.UPDATE_BY
     *
     * @mbggenerated Mon May 05 17:09:26 CST 2014
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_ROLE.UPDATE_DATE
     *
     * @return the value of TT_ROLE.UPDATE_DATE
     *
     * @mbggenerated Mon May 05 17:09:26 CST 2014
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_ROLE.UPDATE_DATE
     *
     * @param updateDate the value for TT_ROLE.UPDATE_DATE
     *
     * @mbggenerated Mon May 05 17:09:26 CST 2014
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_ROLE
     *
     * @mbggenerated Mon May 05 17:09:26 CST 2014
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TtRole other = (TtRole) that;
        return (this.getRoleCode() == null ? other.getRoleCode() == null : this.getRoleCode().equals(other.getRoleCode()))
            && (this.getRoleName() == null ? other.getRoleName() == null : this.getRoleName().equals(other.getRoleName()))
            && (this.getCreateBy() == null ? other.getCreateBy() == null : this.getCreateBy().equals(other.getCreateBy()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
            && (this.getUpdateBy() == null ? other.getUpdateBy() == null : this.getUpdateBy().equals(other.getUpdateBy()))
            && (this.getUpdateDate() == null ? other.getUpdateDate() == null : this.getUpdateDate().equals(other.getUpdateDate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_ROLE
     *
     * @mbggenerated Mon May 05 17:09:26 CST 2014
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getRoleCode() == null) ? 0 : getRoleCode().hashCode());
        result = prime * result + ((getRoleName() == null) ? 0 : getRoleName().hashCode());
        result = prime * result + ((getCreateBy() == null) ? 0 : getCreateBy().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getUpdateBy() == null) ? 0 : getUpdateBy().hashCode());
        result = prime * result + ((getUpdateDate() == null) ? 0 : getUpdateDate().hashCode());
        return result;
    }
}