package com.llsfw.core.model.standard;

import java.io.Serializable;

public class TtUserJobKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_USER_JOB.LOGIN_NAME
     *
     * @mbggenerated Mon May 05 11:25:40 CST 2014
     */
    private String loginName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_USER_JOB.JOB_CODE
     *
     * @mbggenerated Mon May 05 11:25:40 CST 2014
     */
    private String jobCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TT_USER_JOB
     *
     * @mbggenerated Mon May 05 11:25:40 CST 2014
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_USER_JOB.LOGIN_NAME
     *
     * @return the value of TT_USER_JOB.LOGIN_NAME
     *
     * @mbggenerated Mon May 05 11:25:40 CST 2014
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_USER_JOB.LOGIN_NAME
     *
     * @param loginName the value for TT_USER_JOB.LOGIN_NAME
     *
     * @mbggenerated Mon May 05 11:25:40 CST 2014
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_USER_JOB.JOB_CODE
     *
     * @return the value of TT_USER_JOB.JOB_CODE
     *
     * @mbggenerated Mon May 05 11:25:40 CST 2014
     */
    public String getJobCode() {
        return jobCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_USER_JOB.JOB_CODE
     *
     * @param jobCode the value for TT_USER_JOB.JOB_CODE
     *
     * @mbggenerated Mon May 05 11:25:40 CST 2014
     */
    public void setJobCode(String jobCode) {
        this.jobCode = jobCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_USER_JOB
     *
     * @mbggenerated Mon May 05 11:25:40 CST 2014
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TtUserJobKey other = (TtUserJobKey) that;
        return (this.getLoginName() == null ? other.getLoginName() == null : this.getLoginName().equals(other.getLoginName()))
            && (this.getJobCode() == null ? other.getJobCode() == null : this.getJobCode().equals(other.getJobCode()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_USER_JOB
     *
     * @mbggenerated Mon May 05 11:25:40 CST 2014
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getLoginName() == null) ? 0 : getLoginName().hashCode());
        result = prime * result + ((getJobCode() == null) ? 0 : getJobCode().hashCode());
        return result;
    }
}