package com.llsfw.core.mapper.standard;

import com.llsfw.core.model.standard.TtPurview;
import com.llsfw.core.model.standard.TtPurviewCriteria;
import com.llsfw.core.model.standard.TtPurviewKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TtPurviewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_PURVIEW
     *
     * @mbggenerated Mon May 05 11:25:40 CST 2014
     */
    int countByExample(TtPurviewCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_PURVIEW
     *
     * @mbggenerated Mon May 05 11:25:40 CST 2014
     */
    int deleteByExample(TtPurviewCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_PURVIEW
     *
     * @mbggenerated Mon May 05 11:25:40 CST 2014
     */
    int deleteByPrimaryKey(TtPurviewKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_PURVIEW
     *
     * @mbggenerated Mon May 05 11:25:40 CST 2014
     */
    int insert(TtPurview record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_PURVIEW
     *
     * @mbggenerated Mon May 05 11:25:40 CST 2014
     */
    int insertSelective(TtPurview record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_PURVIEW
     *
     * @mbggenerated Mon May 05 11:25:40 CST 2014
     */
    List<TtPurview> selectByExample(TtPurviewCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_PURVIEW
     *
     * @mbggenerated Mon May 05 11:25:40 CST 2014
     */
    TtPurview selectByPrimaryKey(TtPurviewKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_PURVIEW
     *
     * @mbggenerated Mon May 05 11:25:40 CST 2014
     */
    int updateByExampleSelective(@Param("record") TtPurview record, @Param("example") TtPurviewCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_PURVIEW
     *
     * @mbggenerated Mon May 05 11:25:40 CST 2014
     */
    int updateByExample(@Param("record") TtPurview record, @Param("example") TtPurviewCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_PURVIEW
     *
     * @mbggenerated Mon May 05 11:25:40 CST 2014
     */
    int updateByPrimaryKeySelective(TtPurview record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_PURVIEW
     *
     * @mbggenerated Mon May 05 11:25:40 CST 2014
     */
    int updateByPrimaryKey(TtPurview record);
}