package com.llsfw.core.mapper.standard;

import com.llsfw.core.model.standard.TtScheduledTriggerLog;
import com.llsfw.core.model.standard.TtScheduledTriggerLogCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TtScheduledTriggerLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_SCHEDULED_TRIGGER_LOG
     *
     * @mbggenerated Mon May 05 11:25:40 CST 2014
     */
    int countByExample(TtScheduledTriggerLogCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_SCHEDULED_TRIGGER_LOG
     *
     * @mbggenerated Mon May 05 11:25:40 CST 2014
     */
    int deleteByExample(TtScheduledTriggerLogCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_SCHEDULED_TRIGGER_LOG
     *
     * @mbggenerated Mon May 05 11:25:40 CST 2014
     */
    int deleteByPrimaryKey(String logid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_SCHEDULED_TRIGGER_LOG
     *
     * @mbggenerated Mon May 05 11:25:40 CST 2014
     */
    int insert(TtScheduledTriggerLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_SCHEDULED_TRIGGER_LOG
     *
     * @mbggenerated Mon May 05 11:25:40 CST 2014
     */
    int insertSelective(TtScheduledTriggerLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_SCHEDULED_TRIGGER_LOG
     *
     * @mbggenerated Mon May 05 11:25:40 CST 2014
     */
    List<TtScheduledTriggerLog> selectByExample(TtScheduledTriggerLogCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_SCHEDULED_TRIGGER_LOG
     *
     * @mbggenerated Mon May 05 11:25:40 CST 2014
     */
    TtScheduledTriggerLog selectByPrimaryKey(String logid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_SCHEDULED_TRIGGER_LOG
     *
     * @mbggenerated Mon May 05 11:25:40 CST 2014
     */
    int updateByExampleSelective(@Param("record") TtScheduledTriggerLog record, @Param("example") TtScheduledTriggerLogCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_SCHEDULED_TRIGGER_LOG
     *
     * @mbggenerated Mon May 05 11:25:40 CST 2014
     */
    int updateByExample(@Param("record") TtScheduledTriggerLog record, @Param("example") TtScheduledTriggerLogCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_SCHEDULED_TRIGGER_LOG
     *
     * @mbggenerated Mon May 05 11:25:40 CST 2014
     */
    int updateByPrimaryKeySelective(TtScheduledTriggerLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_SCHEDULED_TRIGGER_LOG
     *
     * @mbggenerated Mon May 05 11:25:40 CST 2014
     */
    int updateByPrimaryKey(TtScheduledTriggerLog record);
}